export type LabFeature = {
  id: string;
  name: string;
  description: string;
  category: string;
  emoji: string;
  complexity: 'easy' | 'medium' | 'hard';
  ai: boolean;
  exclusive?: boolean; // heç yerdə yoxdur
};

export const LAB_FEATURES: LabFeature[] = [
  // ═══ 10 EKSKLUZİV — heç yerdə yoxdur ═══
  { id: 'ai-listing-coach', exclusive: true, ai: true, complexity: 'hard', emoji: '🎓', category: 'AI Exclusive', name: 'AI Listing Coach', description: 'Elan yaradanda real-time AI rejissor — copywriting tövsiyələri, A/B variantlar, hansı söz daha çox baxış gətirir, başlıq optimallaşdırması canlı.' },
  { id: 'ai-negotiation-bot', exclusive: true, ai: true, complexity: 'hard', emoji: '🤝', category: 'AI Exclusive', name: 'AI Negotiation Bot', description: 'Siz oflayn olduqda AI sizin əvəzinizdə alıcı ilə danışıq aparır. Min qiymət təyin edirsiz, AI orta yolu tapır, görüş təşkil edir.' },
  { id: 'pricing-war-room', exclusive: true, ai: true, complexity: 'hard', emoji: '⚔️', category: 'AI Exclusive', name: 'AI Pricing War Room', description: 'Real-time rəqib elanlara baxan AI: "İndi qiymət qaldır — rəqib qalxdı", "Endir — 3 yeni daha ucuz elan çıxdı". Bazar canlı izlənilir.' },
  { id: 'buyer-intent-score', exclusive: true, ai: true, complexity: 'medium', emoji: '🎯', category: 'AI Exclusive', name: 'Buyer Intent Score', description: 'Sizə mesaj yazan alıcının AI bal verir (0-100): gerçək alıcı, tamaşaçı, fırıldaqçı, satıcı (konkurent). Mesaj tonu + tarixçə.' },
  { id: 'photo-studio-ai', exclusive: true, ai: true, complexity: 'hard', emoji: '📸', category: 'AI Exclusive', name: 'AI Photo Studio', description: 'Şəkilləri AI ilə premium et: arxa fonu sil, işıqlandır, avtomobil/məhsul studyası fonu yarat. 1 kliklə.' },
  { id: 'voice-to-listing', exclusive: true, ai: true, complexity: 'hard', emoji: '🎙', category: 'AI Exclusive', name: 'Voice-to-Listing', description: '30 saniyə danışırsız: "BMW X5 2020, qara, 80K km, vurğusu yox, 35000 manat". AI tam elan yaradır: başlıq, təsvir, atributlar, kateqoriya.' },
  { id: 'ar-try-before-buy', exclusive: true, ai: true, complexity: 'hard', emoji: '🪞', category: 'AI Exclusive', name: 'AR Try Before Buy', description: 'Telefon kamerası ilə mebel/elektronikanı öz evinizdə virtual yerləşdirin (AR). Almadan əvvəl ölçüləri yoxlayın.' },
  { id: 'sales-forecast', exclusive: true, ai: true, complexity: 'hard', emoji: '🔮', category: 'AI Exclusive', name: 'Predictive Sales Forecast', description: 'AI deyir: "Bu model bu həftə 65% satılacaq" — hava, mövsüm, tarix, bazar trendlərinə əsasən.' },
  { id: 'local-pulse', exclusive: true, ai: true, complexity: 'medium', emoji: '💓', category: 'AI Exclusive', name: 'Local Market Pulse', description: 'Sizin məhəllədə canlı dashboard: kim nə alır, nə satır, qiymət trendi, hot kateqoriyalar.' },
  { id: 'listing-genome', exclusive: true, ai: true, complexity: 'hard', emoji: '🧬', category: 'AI Exclusive', name: 'AI Listing Genome', description: 'Sizin elanın DNK-sını rəqiblərə nisbətən analiz edir: hansı söz/şəkil/atribut daha çox baxış gətirir. Semantik analiz.' },

  // ═══ AI ALƏTLƏRİ (40) ═══
  { id: 'ai-grammar-check', ai: true, complexity: 'easy', emoji: '✍️', category: 'AI', name: 'Qrammatika düzəlişi', description: 'Elan mətnindəki səhvləri AI düzəldir' },
  { id: 'ai-emoji-suggest', ai: true, complexity: 'easy', emoji: '😊', category: 'AI', name: 'Emoji təklif', description: 'Başlığa uyğun emoji-lər təklif edir' },
  { id: 'ai-title-ab-test', ai: true, complexity: 'medium', emoji: '🆎', category: 'AI', name: 'A/B başlıq testi', description: 'AI 3 başlıq variant göstərir, daha effektivi seçirsiz' },
  { id: 'ai-summary', ai: true, complexity: 'easy', emoji: '📝', category: 'AI', name: 'AI xülasə', description: 'Uzun təsviri 3 bullet-ə qısalt (artıq var)' },
  { id: 'ai-translate-auto', ai: true, complexity: 'medium', emoji: '🌐', category: 'AI', name: 'Avto tərcümə', description: 'AZ/RU/EN dillərinə avtomatik' },
  { id: 'ai-keywords', ai: true, complexity: 'easy', emoji: '🔑', category: 'AI', name: 'SEO açar sözləri', description: 'Başlıq+təsvirdən SEO açar sözləri çıxar' },
  { id: 'ai-spam-detect', ai: true, complexity: 'medium', emoji: '🚫', category: 'AI', name: 'Spam detektor', description: 'Şübhəli mesajlara bal verir' },
  { id: 'ai-fraud-score', ai: true, complexity: 'medium', emoji: '🛡', category: 'AI', name: 'Fırıldaq skoru', description: 'Elan üçün AI risk balı (artıq var)' },
  { id: 'ai-photo-rate', ai: true, complexity: 'medium', emoji: '⭐', category: 'AI', name: 'Şəkil keyfiyyət balı', description: 'Şəkillərinizə AI bal verir + iyiləşdirmə tövsiyəsi' },
  { id: 'ai-tag-suggest', ai: true, complexity: 'easy', emoji: '🏷', category: 'AI', name: 'Tag təklif', description: 'AI hashtag və kateqoriya tag-lər təklif edir' },
  { id: 'ai-similar', ai: true, complexity: 'medium', emoji: '🔍', category: 'AI', name: 'AI bənzər elanlar', description: 'Semantik bənzərliklə (artıq var)' },
  { id: 'ai-image-search', ai: true, complexity: 'hard', emoji: '🖼', category: 'AI', name: 'Şəkildən axtarış', description: 'Bir şəkil yüklə, eyni məhsul tap' },
  { id: 'ai-voice-search', ai: true, complexity: 'medium', emoji: '🎙', category: 'AI', name: 'Səsli axtarış', description: 'Səslə filterlər (artıq var)' },
  { id: 'ai-listing-rewrite', ai: true, complexity: 'medium', emoji: '✨', category: 'AI', name: 'Premium yenidən yazma', description: 'AI başlıq+təsviri premium edir (artıq var)' },
  { id: 'ai-rules-check', ai: true, complexity: 'easy', emoji: '✅', category: 'AI', name: 'Qaydalar yoxlaması', description: 'Site qaydalara uyğunluq' },
  { id: 'ai-image-bg-remove', ai: true, complexity: 'hard', emoji: '🪄', category: 'AI', name: 'Şəkildən arxa fonu sil', description: 'Bir kliklə avtomobil/məhsulun arxa fonu silinir' },
  { id: 'ai-image-enhance', ai: true, complexity: 'hard', emoji: '🌟', category: 'AI', name: 'Şəkil HD-yə çevir', description: 'Çətin şəkillər → 4K HD' },
  { id: 'ai-watermark', ai: true, complexity: 'easy', emoji: '💧', category: 'AI', name: 'Avto watermark', description: 'Hər şəkilə brand watermark' },
  { id: 'ai-color-match', ai: true, complexity: 'medium', emoji: '🎨', category: 'AI', name: 'Rəng tanıma', description: 'Şəkildən məhsulun rəngini tap' },
  { id: 'ai-defect-detect', ai: true, complexity: 'hard', emoji: '🔬', category: 'AI', name: 'Qüsur tanıma', description: 'Şəkildə qüsur, qəza izi tap' },
  { id: 'ai-price-suggest', ai: true, complexity: 'medium', emoji: '💰', category: 'AI', name: 'AI qiymət tövsiyəsi', description: 'Bazara görə optimal qiymət' },
  { id: 'ai-best-time', ai: true, complexity: 'easy', emoji: '⏰', category: 'AI', name: 'Ən yaxşı dərc vaxtı', description: 'AI ən aktiv saatı təyin edir' },
  { id: 'ai-forecast', ai: true, complexity: 'medium', emoji: '📈', category: 'AI', name: 'Satış proqnozu', description: 'Bu elan neçə gündə satılacaq' },
  { id: 'ai-buyer-match', ai: true, complexity: 'hard', emoji: '🎯', category: 'AI', name: 'Alıcı uyğunluq', description: 'Elana ən uyğun alıcıları tap (push)' },
  { id: 'ai-chat-reply', ai: true, complexity: 'medium', emoji: '💬', category: 'AI', name: 'AI smart reply', description: 'Chat-da cavab təklifləri (artıq var)' },
  { id: 'ai-summarize-chat', ai: true, complexity: 'medium', emoji: '📋', category: 'AI', name: 'Söhbət xülasəsi', description: 'Uzun söhbəti 3 cümləyə qısalt' },
  { id: 'ai-tone-check', ai: true, complexity: 'medium', emoji: '🎭', category: 'AI', name: 'Tone analizi', description: 'Mesaj tonunu yoxla (kobud/səbirli)' },
  { id: 'ai-handle-rude', ai: true, complexity: 'medium', emoji: '🛑', category: 'AI', name: 'Kobud mesaj bloklama', description: 'Kobud sözlər avto-filter' },
  { id: 'ai-listing-tags', ai: true, complexity: 'easy', emoji: '🔖', category: 'AI', name: 'Avto-tag', description: 'Başlıqdan tag-lər çıxar' },
  { id: 'ai-category-fix', ai: true, complexity: 'easy', emoji: '📁', category: 'AI', name: 'Kateqoriya təklifi', description: 'Səhv kateqoriyada elan → düzgün təklif' },
  { id: 'ai-attribute-fill', ai: true, complexity: 'medium', emoji: '⚙️', category: 'AI', name: 'Atributları doldur', description: 'Başlıqdan il, marka, model çıxar' },
  { id: 'ai-unique-id', ai: true, complexity: 'medium', emoji: '🆔', category: 'AI', name: 'Duplikat aşkar', description: 'Eyni elanı iki yerdə yerləşdirməyi bloklasın' },
  { id: 'ai-deal-recommend', ai: true, complexity: 'medium', emoji: '💎', category: 'AI', name: 'AI deal təklif', description: 'Sizə uyğun elanlar (personalizasiya)' },
  { id: 'ai-similar-faces', ai: true, complexity: 'hard', emoji: '👥', category: 'AI', name: 'Eyni satıcı aşkar', description: 'Fərqli profillərdə eyni şəxsi avatardan tap' },
  { id: 'ai-text-summary-listing', ai: true, complexity: 'easy', emoji: '📃', category: 'AI', name: 'Mövcud listing summary', description: 'Açar nöqtələri 5 saniyəyə oxu' },
  { id: 'ai-listing-q-and-a', ai: true, complexity: 'medium', emoji: '❓', category: 'AI', name: 'AI sual-cavab', description: 'Tipik sualları AI cavablandırır' },
  { id: 'ai-virtual-tour', ai: true, complexity: 'hard', emoji: '🌐', category: 'AI', name: '3D tur generator', description: 'Bir neçə şəkildən 3D tur yarat' },
  { id: 'ai-floor-plan', ai: true, complexity: 'hard', emoji: '📐', category: 'AI', name: 'Floor plan AI', description: 'Mənzil şəkillərindən plan çıxar' },
  { id: 'ai-fashion-suggest', ai: true, complexity: 'medium', emoji: '👗', category: 'AI', name: 'Style match', description: 'Geyim üçün stil təklif' },
  { id: 'ai-trend-prediction', ai: true, complexity: 'hard', emoji: '🔮', category: 'AI', name: 'Trend proqnoz', description: 'Növbəti həftə nə populyar olacaq' },

  // ═══ SƏS/VISION (20) ═══
  { id: 'voice-listing', ai: true, complexity: 'medium', emoji: '🎙', category: 'Voice/Vision', name: 'Səslə elan yarat', description: 'Mikrofona danış, AI elan yaradır' },
  { id: 'voice-chat', ai: false, complexity: 'easy', emoji: '🗣', category: 'Voice/Vision', name: 'Səsli mesaj', description: 'Chat-da 60s səs mesajı' },
  { id: 'voice-broadcast', ai: false, complexity: 'medium', emoji: '📻', category: 'Voice/Vision', name: 'Satıcı pitch', description: 'Elanın 30s səsli təqdimatı' },
  { id: 'voice-translate', ai: true, complexity: 'medium', emoji: '🌍', category: 'Voice/Vision', name: 'Səsli tərcümə', description: 'AZ səsi → RU/EN mətn' },
  { id: 'voice-dictate', ai: true, complexity: 'easy', emoji: '⌨️', category: 'Voice/Vision', name: 'Səsli yazma', description: 'Mesaj danış, yazılı çıxsın' },
  { id: 'cam-vin-scan', ai: true, complexity: 'hard', emoji: '🚗', category: 'Voice/Vision', name: 'Kameradan VIN', description: 'Kamera ilə VIN tara' },
  { id: 'cam-plate', ai: true, complexity: 'hard', emoji: '🔢', category: 'Voice/Vision', name: 'Plaka tarayıcı', description: 'Kamera ilə plaka oxuma' },
  { id: 'cam-barcode', ai: true, complexity: 'medium', emoji: '📊', category: 'Voice/Vision', name: 'Barkod tarayıcı', description: 'Məhsul barkodu tara, məlumat çıxar' },
  { id: 'cam-document', ai: true, complexity: 'hard', emoji: '📄', category: 'Voice/Vision', name: 'Sənəd taram', description: 'Çıxarış/pasport taraması' },
  { id: 'photo-360', ai: false, complexity: 'medium', emoji: '🔄', category: 'Voice/Vision', name: '360° şəkil', description: '360° foto upload' },
  { id: 'video-30s', ai: false, complexity: 'easy', emoji: '🎬', category: 'Voice/Vision', name: '30s video', description: 'Elanlara qısa video' },
  { id: 'reels-stories', ai: false, complexity: 'medium', emoji: '📱', category: 'Voice/Vision', name: 'Stories/Reels', description: 'Instagram-bənzər short' },
  { id: 'live-stream', ai: false, complexity: 'hard', emoji: '📡', category: 'Voice/Vision', name: 'Canlı yayım', description: 'Avtomobili canlı göstər' },
  { id: 'ar-furniture', ai: true, complexity: 'hard', emoji: '🛋', category: 'Voice/Vision', name: 'AR mebel sınama', description: 'Mebeli evdə virtual qoy' },
  { id: 'ar-clothing', ai: true, complexity: 'hard', emoji: '👕', category: 'Voice/Vision', name: 'AR geyim sınama', description: 'Paltarı üzərinə virtual qoy' },
  { id: 'photo-collage', ai: false, complexity: 'easy', emoji: '🖼', category: 'Voice/Vision', name: 'Foto kolaj', description: '4 şəkili 1 grid-də göstər' },
  { id: 'photo-watermark', ai: false, complexity: 'easy', emoji: '💧', category: 'Voice/Vision', name: 'Watermark', description: 'Brand watermark' },
  { id: 'photo-bg-blur', ai: true, complexity: 'medium', emoji: '🌫', category: 'Voice/Vision', name: 'Arxa fonu blur', description: 'Portret mode' },
  { id: 'photo-resize-auto', ai: false, complexity: 'easy', emoji: '📏', category: 'Voice/Vision', name: 'Avto ölçü', description: 'Yüklədikdə düzgün ölçü' },
  { id: 'photo-color-correct', ai: true, complexity: 'medium', emoji: '🎨', category: 'Voice/Vision', name: 'Rəng korreksiya', description: 'Şəkildə işıqlandırmanı düzəlt' },

  // ═══ MARKETING/SEO (20) ═══
  { id: 'seo-meta-gen', ai: true, complexity: 'easy', emoji: '🌐', category: 'Marketing', name: 'AI meta tag', description: 'SEO meta description AI yazır' },
  { id: 'seo-rich-snippet', ai: false, complexity: 'medium', emoji: '⭐', category: 'Marketing', name: 'Rich snippet', description: 'Google star rating görsənmə' },
  { id: 'social-auto-post', ai: false, complexity: 'medium', emoji: '📲', category: 'Marketing', name: 'Avto sosial paylaşım', description: 'FB/IG-yə avto post' },
  { id: 'sticker-share', ai: false, complexity: 'easy', emoji: '🏷', category: 'Marketing', name: 'Sticker pack', description: 'Elan üçün WhatsApp sticker' },
  { id: 'qr-share', ai: false, complexity: 'easy', emoji: '📲', category: 'Marketing', name: 'QR paylaşım', description: 'Elan QR (artıq var)' },
  { id: 'email-blast', ai: false, complexity: 'medium', emoji: '📧', category: 'Marketing', name: 'Email blast', description: 'Filtirli auditoryaya email' },
  { id: 'sms-blast', ai: false, complexity: 'medium', emoji: '💬', category: 'Marketing', name: 'SMS blast', description: 'Hədəfli SMS kampaniya' },
  { id: 'push-segment', ai: false, complexity: 'medium', emoji: '🔔', category: 'Marketing', name: 'Push seqment', description: 'Filtirli istifadəçilərə push' },
  { id: 'referral-code', ai: false, complexity: 'easy', emoji: '🎁', category: 'Marketing', name: 'Referral', description: 'Dostu dəvət et bonus' },
  { id: 'affiliate', ai: false, complexity: 'hard', emoji: '🤝', category: 'Marketing', name: 'Affiliate program', description: 'Linki paylaş, komissiya qazan' },
  { id: 'newsletter', ai: false, complexity: 'easy', emoji: '📰', category: 'Marketing', name: 'Newsletter', description: 'Həftəlik xülasə' },
  { id: 'banner-ads', ai: false, complexity: 'medium', emoji: '📢', category: 'Marketing', name: 'Banner reklam', description: 'Elanı banner et' },
  { id: 'promo-codes', ai: false, complexity: 'easy', emoji: '🎫', category: 'Marketing', name: 'Promo kodlar', description: 'Endirim kuponları' },
  { id: 'gift-cards', ai: false, complexity: 'medium', emoji: '🎁', category: 'Marketing', name: 'Hədiyyə kartları', description: 'Sevdiklərinə kart hədiyyə' },
  { id: 'loyalty-points', ai: false, complexity: 'medium', emoji: '⭐', category: 'Marketing', name: 'Sadiqlik xalları', description: 'Hər satış xal qazandır' },
  { id: 'birthday-promo', ai: false, complexity: 'easy', emoji: '🎂', category: 'Marketing', name: 'Ad günü endirimi', description: 'Yaş gününə xüsusi' },
  { id: 'flash-sale', ai: false, complexity: 'medium', emoji: '⚡', category: 'Marketing', name: 'Flash sale', description: '24 saatlıq endirim' },
  { id: 'bundle-deal', ai: false, complexity: 'medium', emoji: '📦', category: 'Marketing', name: 'Toplu satış', description: '3 al, 1-ni pulsuz' },
  { id: 'price-history-chart', ai: false, complexity: 'medium', emoji: '📊', category: 'Marketing', name: 'Qiymət tarixçəsi', description: 'Qrafik' },
  { id: 'wishlist-alert', ai: false, complexity: 'easy', emoji: '❤️', category: 'Marketing', name: 'Wishlist alert', description: 'Sevimli endirildi xəbər ver' },

  // ═══ ANALYTICS (20) ═══
  { id: 'dashboard-pro', ai: false, complexity: 'medium', emoji: '📊', category: 'Analytics', name: 'Pro dashboard', description: 'Tam analitika ekranı' },
  { id: 'heatmap', ai: false, complexity: 'hard', emoji: '🔥', category: 'Analytics', name: 'Heatmap', description: 'Hara klikləyirlər' },
  { id: 'funnel', ai: false, complexity: 'hard', emoji: '⏬', category: 'Analytics', name: 'Funnel analiz', description: 'Görüntü → Zəng → Satış' },
  { id: 'cohort', ai: false, complexity: 'hard', emoji: '👥', category: 'Analytics', name: 'Cohort analiz', description: 'İstifadəçi qrupları' },
  { id: 'ab-testing', ai: false, complexity: 'hard', emoji: '🆎', category: 'Analytics', name: 'A/B test platforması', description: 'Variant test' },
  { id: 'conversion-rate', ai: false, complexity: 'medium', emoji: '💱', category: 'Analytics', name: 'Konversiya nisbəti', description: 'Görüntü/satış faizi' },
  { id: 'realtime-views', ai: false, complexity: 'medium', emoji: '👁', category: 'Analytics', name: 'Real-time görüntü', description: 'İndi neçə nəfər baxır' },
  { id: 'demographics', ai: false, complexity: 'medium', emoji: '👨‍👩‍👧', category: 'Analytics', name: 'Demoqrafiya', description: 'Yaş, cins, region' },
  { id: 'geo-heatmap', ai: false, complexity: 'hard', emoji: '🗺', category: 'Analytics', name: 'Geo heatmap', description: 'Hansı bölgədən baxırlar' },
  { id: 'device-stats', ai: false, complexity: 'easy', emoji: '📱', category: 'Analytics', name: 'Cihaz stats', description: 'Mobile vs Desktop' },
  { id: 'search-terms', ai: false, complexity: 'medium', emoji: '🔍', category: 'Analytics', name: 'Axtarış terms', description: 'Hansı sözlərlə tapırlar' },
  { id: 'time-on-page', ai: false, complexity: 'easy', emoji: '⏱', category: 'Analytics', name: 'Sayfa vaxtı', description: 'Nə qədər qalırlar' },
  { id: 'bounce-rate', ai: false, complexity: 'easy', emoji: '↩️', category: 'Analytics', name: 'Bounce rate', description: 'Sürətlə tərk edənlər' },
  { id: 'export-csv', ai: false, complexity: 'easy', emoji: '📥', category: 'Analytics', name: 'CSV export', description: 'Stats csv-yə yüklə' },
  { id: 'pdf-report', ai: false, complexity: 'medium', emoji: '📄', category: 'Analytics', name: 'PDF reportı', description: 'Aylıq pdf' },
  { id: 'compare-period', ai: false, complexity: 'medium', emoji: '⚖️', category: 'Analytics', name: 'Dövr müqayisəsi', description: 'Bu ay vs keçən' },
  { id: 'predictive-trend', ai: true, complexity: 'hard', emoji: '🔮', category: 'Analytics', name: 'AI trend proqnoz', description: 'Gələcək həftə proqnozu' },
  { id: 'competitor-tracking', ai: true, complexity: 'hard', emoji: '🥷', category: 'Analytics', name: 'Rəqib izləmə', description: 'Rəqib elanlarını izlə' },
  { id: 'roi-calc', ai: false, complexity: 'medium', emoji: '💵', category: 'Analytics', name: 'ROI kalkulyator', description: 'Reklam xərc/qazanc' },
  { id: 'attribution', ai: false, complexity: 'hard', emoji: '🎯', category: 'Analytics', name: 'Attribution', description: 'Hansı kanaldan gəldi' },

  // ═══ AUTOMATION (20) ═══
  { id: 'auto-renew', ai: false, complexity: 'easy', emoji: '🔄', category: 'Automation', name: 'Avto yeniləmə', description: 'Elan vaxtı bitəndə avto' },
  { id: 'auto-bump', ai: false, complexity: 'easy', emoji: '⬆️', category: 'Automation', name: 'Avto qaldırma', description: 'Hər gün üstə qaldır' },
  { id: 'auto-reply', ai: false, complexity: 'medium', emoji: '🤖', category: 'Automation', name: 'Avto cavab', description: 'Oflayn ikən bot cavablar' },
  { id: 'auto-translate', ai: true, complexity: 'medium', emoji: '🌐', category: 'Automation', name: 'Avto tərcümə', description: 'AZ→RU→EN' },
  { id: 'auto-categorize', ai: true, complexity: 'medium', emoji: '📁', category: 'Automation', name: 'Avto kateqoriya', description: 'AI seçir (artıq var)' },
  { id: 'scheduled-publish', ai: false, complexity: 'medium', emoji: '⏰', category: 'Automation', name: 'Planlaşdırılmış dərc', description: 'Vaxt-saat ilə' },
  { id: 'auto-archive', ai: false, complexity: 'easy', emoji: '📦', category: 'Automation', name: 'Avto arxiv', description: '30 gün sonra arxivlə' },
  { id: 'bulk-edit', ai: false, complexity: 'medium', emoji: '✏️', category: 'Automation', name: 'Toplu redaktə', description: 'Bütün elanlara dəyişiklik' },
  { id: 'bulk-price', ai: false, complexity: 'easy', emoji: '💰', category: 'Automation', name: 'Toplu qiymət', description: '-10% bütün' },
  { id: 'bulk-delete', ai: false, complexity: 'easy', emoji: '🗑', category: 'Automation', name: 'Toplu silmə', description: 'Bir kliklə hamısı' },
  { id: 'duplicate-listing', ai: false, complexity: 'easy', emoji: '📋', category: 'Automation', name: 'Elan kopyala', description: 'Şablon kimi' },
  { id: 'workflow-zapier', ai: false, complexity: 'hard', emoji: '⚙️', category: 'Automation', name: 'Zapier inteqrasiya', description: '5000+ tool-a bağla' },
  { id: 'api-public', ai: false, complexity: 'hard', emoji: '🔌', category: 'Automation', name: 'Public API', description: 'Developer üçün' },
  { id: 'webhook', ai: false, complexity: 'medium', emoji: '🪝', category: 'Automation', name: 'Webhook', description: 'Hadisədə kənar servis çağır' },
  { id: 'rss-feed', ai: false, complexity: 'easy', emoji: '📡', category: 'Automation', name: 'RSS feed', description: 'Avto abunəlik' },
  { id: 'import-excel', ai: false, complexity: 'medium', emoji: '📊', category: 'Automation', name: 'Excel import', description: 'Toplu xlsx-dən' },
  { id: 'import-csv', ai: false, complexity: 'medium', emoji: '📄', category: 'Automation', name: 'CSV import', description: 'CSV-dən elan əlavə' },
  { id: 'scrape-other-sites', ai: true, complexity: 'hard', emoji: '🕷', category: 'Automation', name: 'Sayt parsing', description: 'Bina.az-dan auto import' },
  { id: 'auto-respond-time', ai: false, complexity: 'medium', emoji: '⏳', category: 'Automation', name: 'Cavab vaxtı tracker', description: 'Ortalama 5 dəq' },
  { id: 'follow-up-bot', ai: true, complexity: 'medium', emoji: '🔁', category: 'Automation', name: 'Follow-up bot', description: '2 gün sonra yazsa xatırlat' },

  // ═══ COMMUNICATION (15) ═══
  { id: 'chat-realtime', ai: false, complexity: 'medium', emoji: '💬', category: 'Communication', name: 'Real-time chat', description: 'Socket.io ilə canlı' },
  { id: 'video-call', ai: false, complexity: 'hard', emoji: '📹', category: 'Communication', name: 'Video zəng', description: 'Browser-də WebRTC' },
  { id: 'voice-call', ai: false, complexity: 'hard', emoji: '📞', category: 'Communication', name: 'Səsli zəng', description: 'Brauzer-də zəng' },
  { id: 'group-chat', ai: false, complexity: 'medium', emoji: '👥', category: 'Communication', name: 'Qrup chat', description: 'Birgə alış üçün' },
  { id: 'meeting-schedule', ai: false, complexity: 'medium', emoji: '📅', category: 'Communication', name: 'Görüş təyini', description: 'Calendar inteqrasiya' },
  { id: 'translation-chat', ai: true, complexity: 'medium', emoji: '🌐', category: 'Communication', name: 'Chat tərcümə', description: 'Anlıq AZ↔RU↔EN' },
  { id: 'sticker-pack', ai: false, complexity: 'easy', emoji: '🐶', category: 'Communication', name: 'Stiker', description: 'Pulsuz stikerlər' },
  { id: 'gif-search', ai: false, complexity: 'easy', emoji: '🎬', category: 'Communication', name: 'GIF axtarış', description: 'GIPHY inteqrasiya' },
  { id: 'audio-message', ai: false, complexity: 'easy', emoji: '🎤', category: 'Communication', name: 'Audio mesaj', description: '60s səs' },
  { id: 'file-share', ai: false, complexity: 'medium', emoji: '📎', category: 'Communication', name: 'Fayl paylaşım', description: 'PDF, doc' },
  { id: 'location-share', ai: false, complexity: 'medium', emoji: '📍', category: 'Communication', name: 'Yer paylaşım', description: 'Canlı GPS' },
  { id: 'contact-share', ai: false, complexity: 'easy', emoji: '👤', category: 'Communication', name: 'Kontakt paylaş', description: 'vCard' },
  { id: 'read-receipt', ai: false, complexity: 'easy', emoji: '✓✓', category: 'Communication', name: 'Oxundu', description: 'WhatsApp stil' },
  { id: 'typing-indicator', ai: false, complexity: 'easy', emoji: '⌨️', category: 'Communication', name: 'Yazır...', description: 'Canlı status' },
  { id: 'block-user', ai: false, complexity: 'easy', emoji: '🚫', category: 'Communication', name: 'İstifadəçi blok', description: 'Söhbəti kəs' },

  // ═══ PERSONALIZATION (15) ═══
  { id: 'theme-light', ai: false, complexity: 'easy', emoji: '☀️', category: 'Personal', name: 'Aydın mövzu', description: 'Default light' },
  { id: 'theme-dark', ai: false, complexity: 'easy', emoji: '🌙', category: 'Personal', name: 'Tünd mövzu', description: 'GitHub stil' },
  { id: 'theme-sepia', ai: false, complexity: 'easy', emoji: '📜', category: 'Personal', name: 'Sepia', description: 'Gözə xoş' },
  { id: 'theme-system', ai: false, complexity: 'easy', emoji: '🖥', category: 'Personal', name: 'Sistemə görə', description: 'Avto' },
  { id: 'density-compact', ai: false, complexity: 'easy', emoji: '📦', category: 'Personal', name: 'Kompakt görünüş', description: 'Daha çox info' },
  { id: 'lite-mode', ai: false, complexity: 'medium', emoji: '🌟', category: 'Personal', name: 'Lite rejim', description: 'Sadə UX' },
  { id: 'pro-mode', ai: false, complexity: 'medium', emoji: '⚡', category: 'Personal', name: 'Pro rejim', description: 'Bütün funksiyalar' },
  { id: 'lang-az', ai: false, complexity: 'easy', emoji: '🇦🇿', category: 'Personal', name: 'Azərbaycan dili', description: 'AZ' },
  { id: 'lang-ru', ai: false, complexity: 'easy', emoji: '🇷🇺', category: 'Personal', name: 'Русский язык', description: 'RU' },
  { id: 'lang-en', ai: false, complexity: 'easy', emoji: '🇬🇧', category: 'Personal', name: 'English', description: 'EN' },
  { id: 'currency-azn', ai: false, complexity: 'easy', emoji: '₼', category: 'Personal', name: 'AZN valyuta', description: 'manat' },
  { id: 'currency-usd', ai: false, complexity: 'easy', emoji: '$', category: 'Personal', name: 'USD', description: 'dollar' },
  { id: 'currency-eur', ai: false, complexity: 'easy', emoji: '€', category: 'Personal', name: 'EUR', description: 'avro' },
  { id: 'fav-categories', ai: false, complexity: 'easy', emoji: '⭐', category: 'Personal', name: 'Sevimli kateqoriyalar', description: 'Pin et' },
  { id: 'custom-feed', ai: true, complexity: 'medium', emoji: '🎨', category: 'Personal', name: 'Şəxsi feed', description: 'AI sizin üçün' },

  // ═══ REAL ESTATE (10) ═══
  { id: 'mortgage-calc', ai: false, complexity: 'easy', emoji: '🏦', category: 'Real Estate', name: 'İpoteka kalkulyator', description: 'Aylıq ödəniş' },
  { id: 'preapproval', ai: false, complexity: 'medium', emoji: '✅', category: 'Real Estate', name: 'Pre-approval', description: 'Nə qədər ala bilərsiz' },
  { id: 'neighborhood-score', ai: true, complexity: 'medium', emoji: '🏘', category: 'Real Estate', name: 'Məhəllə qiymət', description: '5 oxda' },
  { id: 'walk-score', ai: false, complexity: 'medium', emoji: '🚶', category: 'Real Estate', name: 'Walk score', description: 'Piyada gəzilməsi' },
  { id: 'schools-nearby', ai: false, complexity: 'medium', emoji: '🏫', category: 'Real Estate', name: 'Yaxın məktəblər', description: 'Reytinq' },
  { id: 'price-heatmap', ai: false, complexity: 'medium', emoji: '🔥', category: 'Real Estate', name: 'Qiymət heatmap', description: 'Bakı rayonları' },
  { id: 'price-trend', ai: false, complexity: 'medium', emoji: '📈', category: 'Real Estate', name: '12 ay trend', description: 'Qiymət dinamikası' },
  { id: 'virtual-tour-360', ai: false, complexity: 'hard', emoji: '🌐', category: 'Real Estate', name: '360° tur', description: 'Pannellum' },
  { id: 'floor-plan-3d', ai: true, complexity: 'hard', emoji: '🏠', category: 'Real Estate', name: '3D mənzil planı', description: 'Şəkillərdən' },
  { id: 'mortgage-shop', ai: false, complexity: 'hard', emoji: '🏦', category: 'Real Estate', name: 'Bank müqayisə', description: 'Ən yaxşı faiz' },

  // ═══ AUTO (10) ═══
  { id: 'vin-check', ai: false, complexity: 'medium', emoji: '🔍', category: 'Auto', name: 'VIN check', description: 'Tarixçə' },
  { id: 'plate-lookup', ai: false, complexity: 'medium', emoji: '🔢', category: 'Auto', name: 'Plaka', description: 'Region/sahib' },
  { id: 'car-history', ai: true, complexity: 'hard', emoji: '📋', category: 'Auto', name: 'Car History', description: 'Qəza, servis, sahib' },
  { id: 'fuel-cost', ai: false, complexity: 'easy', emoji: '⛽', category: 'Auto', name: 'Yanacaq kalk.', description: 'Aylıq xərc' },
  { id: 'insurance-calc', ai: false, complexity: 'medium', emoji: '🛡', category: 'Auto', name: 'Sığorta', description: 'KASKO/OSAGO' },
  { id: 'service-schedule', ai: false, complexity: 'medium', emoji: '🔧', category: 'Auto', name: 'Servis cədvəli', description: 'Yağ, filtr' },
  { id: 'recall-check', ai: false, complexity: 'medium', emoji: '⚠️', category: 'Auto', name: 'Recall yoxla', description: 'Geri çağırış' },
  { id: 'tire-size', ai: false, complexity: 'easy', emoji: '🛞', category: 'Auto', name: 'Təkər ölçü', description: 'Marka/modelə görə' },
  { id: 'parts-finder', ai: false, complexity: 'hard', emoji: '🔩', category: 'Auto', name: 'Detal tap', description: 'OEM nömrəsi' },
  { id: 'dealer-locator', ai: false, complexity: 'medium', emoji: '🏪', category: 'Auto', name: 'Diler tap', description: 'Yaxın saloınlar' },

  // ═══ JOB (10) ═══
  { id: 'resume-builder', ai: true, complexity: 'medium', emoji: '📄', category: 'Job', name: 'CV yaradıcı', description: 'AI köməyi ilə' },
  { id: 'cover-letter-ai', ai: true, complexity: 'medium', emoji: '✉️', category: 'Job', name: 'Cover letter AI', description: 'Vakansiyaya görə' },
  { id: 'salary-bench', ai: false, complexity: 'medium', emoji: '💰', category: 'Job', name: 'Maaş analizi', description: 'Bazara nisbətən' },
  { id: 'interview-prep', ai: true, complexity: 'medium', emoji: '🎤', category: 'Job', name: 'İnterview hazırlıq', description: 'AI suallar' },
  { id: 'skill-test', ai: false, complexity: 'hard', emoji: '🎓', category: 'Job', name: 'Bacarıq testləri', description: 'Sertifikat' },
  { id: 'company-rating', ai: false, complexity: 'medium', emoji: '⭐', category: 'Job', name: 'Şirkət rey', description: 'Anonim rəylər' },
  { id: 'job-alerts', ai: false, complexity: 'easy', emoji: '🔔', category: 'Job', name: 'Vakansiya alert', description: 'Yeni iş gələndə' },
  { id: 'one-click-apply', ai: false, complexity: 'medium', emoji: '✨', category: 'Job', name: '1-Kliklə müraciət', description: 'CV avto' },
  { id: 'video-cv', ai: false, complexity: 'hard', emoji: '🎬', category: 'Job', name: 'Video CV', description: '60s təqdimat' },
  { id: 'referral-jobs', ai: false, complexity: 'medium', emoji: '🤝', category: 'Job', name: 'İş referralı', description: 'Dostu yönləndir bonus' },

  // ═══ TRUST & SAFETY (10) ═══
  { id: 'verified-seller', ai: false, complexity: 'medium', emoji: '🛡', category: 'Trust', name: 'Təsdiqli satıcı', description: 'Sənəd yoxlanılıb' },
  { id: 'id-verification', ai: true, complexity: 'hard', emoji: '🆔', category: 'Trust', name: 'ID yoxlanış', description: 'Sənəd + selfie' },
  { id: 'phone-verify', ai: false, complexity: 'easy', emoji: '📱', category: 'Trust', name: 'Telefon təsdiq', description: 'SMS OTP' },
  { id: 'email-verify', ai: false, complexity: 'easy', emoji: '📧', category: 'Trust', name: 'E-poçt təsdiq', description: 'Link' },
  { id: 'fraud-detect', ai: true, complexity: 'hard', emoji: '🚨', category: 'Trust', name: 'AI fırıldaq', description: 'Şübhəli aktivlik' },
  { id: 'report-abuse', ai: false, complexity: 'easy', emoji: '⚠️', category: 'Trust', name: 'Şikayət', description: 'Spam/saxta' },
  { id: 'block-user', ai: false, complexity: 'easy', emoji: '🚫', category: 'Trust', name: 'Bloklama', description: 'İstifadəçi blok' },
  { id: 'safe-pay-badge', ai: false, complexity: 'medium', emoji: '🔒', category: 'Trust', name: 'Təhlükəsiz ödəniş', description: 'Escrow badge' },
  { id: 'trust-score-public', ai: false, complexity: 'medium', emoji: '⭐', category: 'Trust', name: 'Public etibar balı', description: '0-100' },
  { id: 'background-check', ai: false, complexity: 'hard', emoji: '🔍', category: 'Trust', name: 'Background check', description: 'Tarixçə yoxla' },

  // ═══ PAYMENT (10) ═══
  { id: 'escrow', ai: false, complexity: 'hard', emoji: '🔐', category: 'Payment', name: 'Escrow', description: 'Pul orta-da saxla' },
  { id: 'crypto-pay', ai: false, complexity: 'hard', emoji: '₿', category: 'Payment', name: 'Crypto ödəniş', description: 'BTC/ETH' },
  { id: 'card-pay', ai: false, complexity: 'medium', emoji: '💳', category: 'Payment', name: 'Kart ödəniş', description: 'Visa/MC' },
  { id: 'mobile-pay', ai: false, complexity: 'medium', emoji: '📱', category: 'Payment', name: 'Mobil ödəniş', description: 'M10/HesabKart' },
  { id: 'installment', ai: false, complexity: 'medium', emoji: '📊', category: 'Payment', name: 'Hissə-hissə', description: '12 ay 0%' },
  { id: 'paypal', ai: false, complexity: 'medium', emoji: '💲', category: 'Payment', name: 'PayPal', description: 'Beynəlxalq' },
  { id: 'invoice', ai: false, complexity: 'medium', emoji: '🧾', category: 'Payment', name: 'Hesab-faktura', description: 'PDF qaimə' },
  { id: 'refund', ai: false, complexity: 'medium', emoji: '↩️', category: 'Payment', name: 'Geri qaytarma', description: '7 gün' },
  { id: 'split-pay', ai: false, complexity: 'hard', emoji: '👥', category: 'Payment', name: 'Birgə ödəniş', description: 'Bir neçə nəfər' },
  { id: 'wallet', ai: false, complexity: 'medium', emoji: '👛', category: 'Payment', name: 'Daxili wallet', description: '360tap balans' },
];

export const LAB_CATEGORIES = [
  { id: 'AI Exclusive',   emoji: '🚀', color: 'from-violet-500 to-tap', accent: 'text-violet-600 bg-violet-50' },
  { id: 'AI',             emoji: '🤖', color: 'from-tap to-cyan-400',    accent: 'text-tap bg-tap-50' },
  { id: 'Voice/Vision',   emoji: '🎙', color: 'from-pink-500 to-rose-400',accent: 'text-pink-600 bg-pink-50' },
  { id: 'Marketing',      emoji: '📢', color: 'from-amber-400 to-orange-500',accent: 'text-orange-600 bg-orange-50' },
  { id: 'Analytics',      emoji: '📊', color: 'from-blue-500 to-indigo-400',accent: 'text-blue-600 bg-blue-50' },
  { id: 'Automation',     emoji: '⚙️', color: 'from-emerald-500 to-teal-400',accent: 'text-emerald-600 bg-emerald-50' },
  { id: 'Communication',  emoji: '💬', color: 'from-violet-400 to-purple-500',accent: 'text-violet-600 bg-violet-50' },
  { id: 'Personal',       emoji: '🎨', color: 'from-rose-400 to-pink-500',accent: 'text-rose-600 bg-rose-50' },
  { id: 'Real Estate',    emoji: '🏠', color: 'from-blue-400 to-cyan-500',accent: 'text-blue-600 bg-blue-50' },
  { id: 'Auto',           emoji: '🚗', color: 'from-red-500 to-orange-400',accent: 'text-red-600 bg-red-50' },
  { id: 'Job',            emoji: '💼', color: 'from-slate-500 to-slate-700',accent: 'text-slate-700 bg-slate-100' },
  { id: 'Trust',          emoji: '🛡', color: 'from-emerald-500 to-green-400',accent: 'text-emerald-600 bg-emerald-50' },
  { id: 'Payment',        emoji: '💰', color: 'from-amber-500 to-yellow-400',accent: 'text-amber-600 bg-amber-50' },
];

export const TOTAL = LAB_FEATURES.length;
